### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by natestemen** [MarkJr94/torus#1]
Hey there,

I would like to use this tool, but am not really all that familiar with rust and am not really sure how to install it?

Any tips?

**Comment by MarkJr94** [comment]
Hey, if you are willing to install the Rust toolchain, you can follow the easy steps here: https://rustup.rs/

And then once cargo (the Rust package manager+build tool) is installed, just run `cargo install torus`.

If you would prefer not to do that, I'd be happy to set up proper builds to create a deployable binary, if you'd be willing to wait for that.

**Comment by natestemen** [comment]
Hey, I've installed rust and cargo along with it, but `cargo install torus` doesn't seem to find this project.

```bash
$ cargo install torus
    Updating crates.io index
error: could not find `torus` in registry `https://github.com/rust-lang/crates.io-index`
```

Is there something else I need to do?

Thanks for the help!

**Comment by MarkJr94** [comment]
No I need to actually upload it to the crates.io repo, I thought I had published it! Sorry for the wait, I have been away from home. I'll likely get to it Monday. I'd also really appreciate any feedback on features to add and so on if you have any!

**Comment by MarkJr94** [comment]
@natestemen  `cargo install torus` should work now

**Comment by natestemen** [comment]
Cool that seemed to have worked. Will definitely submit feedback as I use the tool. Thanks so much for getting it up!
